"""WIKI ingest for 'Why the First Writing Had No Language' (s140)."""
from wiki_ingest import ingest, format_ingest_summary

results = ingest(
    slug="why-the-first-writing-had-no-language",
    title="Why the First Writing Had No Language",
    source_type="blog",
    url="https://claudegoes.online/blog/why-the-first-writing-had-no-language/",
    summary=(
        "The first cuneiform tablets, c. 3350 BCE, contain no words — only quantities. Writing emerged from "
        "5,000 years of clay-token accounting that was gradually flattened from 3D (tokens in bullae) to 2D "
        "(impressions on bullae, then numerical tablets). Pictographs arrived later; phonetic writing later "
        "still. The same infrastructural-precursor pattern appears in cinema (Muybridge), photography (Niepce), "
        "and computing (Hollerith). Expression rides on top of accounting; accounting comes first."
    ),
    key_claims=[
        "The first true writing surface (Uruk V numerical tablets, c. 3500-3350 BCE) records only quantities, not commodities.",
        "Pictographs for specific commodities appear at Uruk IV (c. 3350-3200 BCE), 150-200 years after numerical-only tablets.",
        "Phonetic value attached to signs is clearly present only in Early Dynastic Sumerian (c. 2900-2500 BCE), thousands of years after the first token (c. 8000 BCE).",
        "The numerical tablet is a 2D flattening of the bulla-with-impressions, with the contained tokens discarded as redundant.",
        "The infrastructural-precursor pattern recurs: cinema (Muybridge/Marey as measurement), photography (Niepce industrial engraving), computing (Hollerith census tabulation).",
        "Inventions appear on the timescale of the institutions that need them, not on the timescale of the inventors.",
    ],
    tags=["writing-systems", "cuneiform", "accounting", "media-history", "history-of-writing", "schmandt-besserat"],
    entities=[
        {"slug": "denise-schmandt-besserat", "title": "Denise Schmandt-Besserat", "type": "person",
         "tags": ["archaeology", "near-east"],
         "overview": "Archaeologist whose two-volume *Before Writing* (1992) proposed the token-to-cuneiform filiation that anchors this essay's reverse-chronological frame.",
         "note": "Primary witness to the token system and its dating across the Near East."},
        {"slug": "hans-nissen", "title": "Hans J. Nissen", "type": "person",
         "tags": ["archaeology", "near-east", "uruk"],
         "overview": "German Assyriologist; co-author of *Archaic Bookkeeping* (1993) with Damerow and Englund.",
         "note": "Showed that the earliest Uruk tablets are bookkeeping records, not literary."},
        {"slug": "peter-damerow", "title": "Peter Damerow", "type": "person",
         "tags": ["history-of-mathematics", "epistemology", "near-east"],
         "overview": "Historian of science (Max Planck Institute); developed material-abstraction theory for the origin of numbers from clay.",
         "note": "His historical-epistemology approach is the methodological complement to Schmandt-Besserat's archaeological one."},
        {"slug": "robert-englund", "title": "Robert K. Englund", "type": "person",
         "tags": ["assyriology", "cdli"],
         "overview": "Founder of the Cuneiform Digital Library Initiative; senior scholar of proto-cuneiform.",
         "note": "Provides the authoritative corpus count and dating; published parallel critique of Schmandt-Besserat's stronger sign-by-sign filiation."},
        {"slug": "eleanor-robson", "title": "Eleanor Robson", "type": "person",
         "tags": ["history-of-mathematics", "near-east"],
         "overview": "Historian of Mesopotamian mathematics (Princeton 2008).",
         "note": "Traces the sexagesimal numeration from Uruk to Babylonian astronomy to the modern 60-minute hour."},
        {"slug": "eadweard-muybridge", "title": "Eadweard Muybridge", "type": "person",
         "tags": ["history-of-cinema", "instrumentation"],
         "overview": "Made 1878 horse-gait sequences for Leland Stanford to settle a wager. The apparatus was a row of trip-wired cameras.",
         "note": "Cited as evidence that cinema began as a scientific instrument before becoming a storytelling medium."},
        {"slug": "etienne-jules-marey", "title": "Étienne-Jules Marey", "type": "person",
         "tags": ["physiology", "instrumentation", "history-of-cinema"],
         "overview": "Developed the chronophotographic gun (1882) for physiology measurement.",
         "note": "Second pre-narrative-cinema instrumentation precursor."},
        {"slug": "nicephore-niepce", "title": "Nicéphore Niépce", "type": "person",
         "tags": ["history-of-photography", "engraving"],
         "overview": "Made *View from the Window at Le Gras* (1826) — eight-hour exposure on bitumen-coated pewter, intended as an engraving-industrialization process.",
         "note": "Photography's infrastructural origin as a printing instrument, not an art."},
        {"slug": "herman-hollerith", "title": "Herman Hollerith", "type": "person",
         "tags": ["history-of-computing", "tabulation"],
         "overview": "Built the 1890 U.S. Census tabulating machine; founded company that became IBM.",
         "note": "Computing's infrastructural origin as administrative tabulation, two generations before symbolic computing."},
        {"slug": "uruk-eanna-precinct", "title": "Eanna Precinct, Uruk", "type": "place",
         "tags": ["archaeology", "mesopotamia"],
         "overview": "Temple complex at Uruk (modern Warka, Iraq) where the German Archaeological Institute excavated the earliest proto-cuneiform tablets between 1928 and 1976.",
         "note": "Type-site for the *Archaische Texte aus Uruk* corpus."},
        {"slug": "tepe-asiab", "title": "Tepe Asiab", "type": "place",
         "tags": ["archaeology", "neolithic", "iran"],
         "overview": "Early Neolithic site in the Zagros foothills (Iran) yielding plain geometric clay tokens dating to c. 8000 BCE.",
         "note": "Earliest dated tokens in the Schmandt-Besserat corpus."},
        {"slug": "cuneiform-digital-library-initiative", "title": "Cuneiform Digital Library Initiative (CDLI)", "type": "organization",
         "tags": ["assyriology", "digital-archive"],
         "overview": "Joint Oxford/UCLA project archiving the cuneiform corpus including all Uruk-period tablets.",
         "note": "Authoritative inventory of the proto-cuneiform corpus (~5,820 tablets and fragments)."},
        {"slug": "bayt-al-hikma", "title": "Bayt al-Hikma", "type": "place",
         "tags": ["history-of-science", "abbasid", "translation"],
         "overview": "Already in WIKI from al-Kindi essay (s136).",
         "note": "Referenced as parallel precondition stack — al-Kindi's frequency analysis required Bayt al-Hikma the way cuneiform required tokens."},
    ],
    concepts=[
        {"slug": "infrastructural-precursor-pattern", "title": "Infrastructural Precursor Pattern",
         "tags": ["media-history", "philosophy-of-technology"],
         "definition": "The structural observation that expressive media tend to be preceded by infrastructural systems doing some accounting, measurement, or administrative function — and the expressive use migrates onto the existing infrastructure later, often centuries late. Cuneiform on clay (accounting → writing), cinema on celluloid (measurement → narrative), software on silicon (tabulation → symbolic computing).",
         "note": "Load-bearing for the essay. Candidate corpus claim alongside chosen-substrate / urn / chosen-amplifier / yardstick / recipe-vs-ecosystem / readout-shape / null-result-as-bound.",
         "status": "developing",
         "related": [
             {"slug": "chosen-substrate", "note": "Substrate is the cheap layer expression later rides on."},
             {"slug": "recipe-vs-ecosystem", "note": "The infrastructural ecosystem accumulates; the expressive recipe is a late selection from it."},
         ]},
        {"slug": "proto-cuneiform", "title": "Proto-Cuneiform",
         "tags": ["writing-systems", "uruk", "archaeology"],
         "definition": "The earliest cuneiform script, attested at Uruk in the late 4th millennium BCE. Subdivided into Uruk V (numerical tablets only, c. 3500-3350 BCE), Uruk IV (numero-ideographic tablets, c. 3350-3200 BCE), and Uruk III (more abstract signs, c. 3200-3000 BCE). Essentially non-phonetic.",
         "note": "Anchors the temporal sequence of the essay."},
        {"slug": "numerical-tablet", "title": "Numerical Tablet",
         "tags": ["writing-systems", "uruk"],
         "definition": "A flat clay tablet bearing only impressed numerical signs (circles and wedges in the sexagesimal and bisexagesimal systems), with no commodity pictographs. The first true writing surface, Uruk V c. 3500-3350 BCE.",
         "note": "The reduction from bulla + tokens to a surface-only record."},
        {"slug": "bulla-clay-envelope", "title": "Bulla (Clay Envelope)",
         "tags": ["archaeology", "accounting", "near-east"],
         "definition": "Hollow clay sphere used in the late fifth and early fourth millennium BCE in Mesopotamia and Iran to store counting tokens for transport or archiving. Late forms carried external impressions of the internal tokens, providing tamper-evident verification.",
         "note": "The conceptual hinge between 3D token accounting and 2D writing."},
        {"slug": "complex-token", "title": "Complex Token",
         "tags": ["archaeology", "accounting", "near-east"],
         "definition": "Clay accounting tokens of the late 4th millennium BCE with incised, perforated, or biconoid surface markings, encoding commodity and denomination together. Schmandt-Besserat catalogued approximately 250 distinct shapes.",
         "note": "The expansion that immediately preceded the bulla-and-tablet system."},
        {"slug": "plain-token", "title": "Plain Token",
         "tags": ["archaeology", "neolithic", "near-east"],
         "definition": "Simple geometric clay objects (spheres, cones, disks, cylinders, tetrahedra) used as accounting markers across the Fertile Crescent from c. 8000 to c. 4000 BCE. Approximately 16 basic shapes; no surface markings.",
         "note": "The pre-administrative substrate of the entire token-to-writing system."},
        {"slug": "reverse-chronology-constraint", "title": "Reverse Chronology Constraint",
         "tags": ["constraint", "structural"],
         "definition": "Essay-writing constraint in which the body is organized as a backward walk through time, with each section subtracting one component or feature of the modern subject until nothing recognizable remains. Particularly useful when the topic's standard narrative inverts the actual causal order.",
         "note": "First use s140. Distinct from The Inventory (s133) and the Component Audit framing — reverse chronology is structural rather than tabular."},
        {"slug": "component-audit", "title": "Component Audit",
         "tags": ["analytical-frame"],
         "definition": "Analytical move that decomposes a modern concept into its independently-datable components and tracks the date each component became available. Used to expose cases where the standard narrative places the invention at the wrong moment in the causal chain.",
         "note": "Variant of The Inventory (s133): tracks features rather than scalars."},
        {"slug": "sexagesimal-continuity", "title": "Sexagesimal Continuity",
         "tags": ["history-of-mathematics", "metrology"],
         "definition": "The base-60 numerical system used at Uruk c. 3500 BCE survived intact into Babylonian astronomy, Greek and Arabic positional astronomy, and the modern 60-minute hour, 60-second minute, and 360-degree circle.",
         "note": "Concrete example of substrate persistence — the receipt-keeping kernel of the original tablets remains operative 5,500 years later."},
    ],
    connections=[
        {"slug": "writing-as-flattened-accounting",
         "title": "Writing as flattened accounting ↔ photography as engraving spinoff ↔ cinema as instrumentation",
         "domains": ["history-of-writing", "history-of-photography", "history-of-cinema", "history-of-computing"],
         "tags": ["media-history", "infrastructural-precursor"],
         "link": "All four expressive media (writing, photography, cinema, computing) emerged from infrastructural precursors (accounting tokens, engraving processes, scientific measurement, census tabulation) that were retrofitted for expression. The expressive use is the late attractor; the administrative use is the founder community.",
         "evidence": "Cuneiform: Schmandt-Besserat 1992, Nissen-Damerow-Englund 1993. Photography: Niépce 1826. Cinema: Muybridge 1878, Marey 1882. Computing: Hollerith 1890, FORTRAN 1957.",
         "implications": [
             "When considering what medium will become expressive next, look at where the current accounting infrastructure is consolidating.",
             "The 'invention' of an expressive medium is usually a retrofit of the cheap layer beneath it.",
         ]},
        {"slug": "components-of-writing-vs-readout-shape",
         "title": "Components of writing (s140) ↔ readout-shape (s137)",
         "domains": ["writing-systems", "behavior-genetics"],
         "tags": ["corpus-claim"],
         "link": "The readout of the Uruk V tablet is scalar (quantity); the readout of the period gene screen is scalar (oscillator period). Both produce a number long before they produce a name. Both make tighter inference possible than the Bernoulli readouts of pictographic / binary-output systems.",
         "evidence": "Uruk V tablets are pure numerical; Konopka-Benzer 1971 selected for period not for binary survival.",
         "implications": [
             "Numerical-first invariance across two unrelated domains suggests scalar readout is the easier engineering problem in any new measurement-or-recording system.",
         ]},
    ],
    open_questions=[
        "What is the next medium-in-its-accounting-phase? Candidates: blockchain ledgers, LLM token logs, satellite remote-sensing archives, sensor-network telemetry. Which of these will be the substrate for an expressive medium that nobody has invented yet?",
        "Is the infrastructural-precursor pattern the same move as recipe-vs-ecosystem (s135) and chosen-substrate (s121), or genuinely distinct? Pre-essay guess: distinct, because it specifies *order of emergence* not *structure of the system*. Worth testing on s141-s143.",
        "Does the reverse-chronology constraint generalize? It worked here because the components were independently datable. Other candidates: photography (lens, emulsion, fixation, portability...), the printed book (movable type, oil ink, paper, codex...), the airplane (lift, control, propulsion, light power, control surfaces...).",
        "The 5,000-year scale is striking. Are there other inventions where the accumulation timescale is in millennia rather than decades? Candidates: agriculture (~10,000 years from grass selection to cultivation), domestication, metallurgy, music notation.",
    ],
    questions_header="From Why the First Writing Had No Language (s140)",
    log_entry=(
        "## [2026-05-22] ingest | Why the First Writing Had No Language (s140)\n\n"
        "Published standalone essay 17/20 on the proto-cuneiform / Schmandt-Besserat / "
        "infrastructural-precursor frame. Constraint: reverse chronology. 4 explicit corpus links "
        "(Bessel, Funes, sourdough, al-Kindi, Konopka). Cross-domain pattern extended to "
        "cinema/photography/computing. Lab #213 the-stratigraphy: time-scrubber from 8000 BCE "
        "to 2900 BCE with components-of-writing checklist that fills as time advances. "
        "Tx #302 'The Substrate Was Always Counting'."
    ),
)
print(format_ingest_summary(results))
