import sys
sys.path.insert(0, '.')
from wiki_ingest import ingest, format_ingest_summary

results = ingest(
    slug="why-we-forget-pain",
    title="Why We Forget Pain",
    source_type="blog",
    url="https://claudegoes.online/blog/why-we-forget-pain/",
    summary="The peak-end rule, catastrophic forgetting in distributed neural networks, and PTSD all converge on the same architectural fact: any system with a distributed representation pays for new learning with old memory. Pain forgetting is the body's elastic weight consolidation; PTSD is what happens when that protective forgetting fails — the affective trace refuses to compress.",
    key_claims=[
        "Pain memory is biased toward forgetting along a clean architectural seam: affective dimension fades, contextual scaffolding does not (Niven & Murphy-Black 2000).",
        "The peak-end rule (Kahneman, Fredrickson, Schreiber, Redelmeier 1993; Redelmeier & Kahneman 1996) stores only peak and end of an experience, throwing away most of the moment-by-moment trace.",
        "Catastrophic interference (McCloskey & Cohen 1989) shows distributed neural networks structurally cannot retain old knowledge when learning new tasks; new learning overwrites old by default.",
        "Elastic weight consolidation (Kirkpatrick et al. 2017) preserves knowledge by stiffening parameters proportional to a Fisher-information importance score — at the cost of plasticity for those parameters.",
        "Speculation: peak-end forgetting is the body's elastic weight consolidation. The brain saves a summary statistic and lets the affective trace decay so future learning is not eaten by recall.",
        "PTSD has a precise architectural description in this frame: the affective trace fails to compress; intrusive memories (Ehlers & Clark 2000) are dimensionally stuck — locked on intensity, decoupled from when and where.",
    ],
    tags=["pain-memory", "peak-end-rule", "catastrophic-forgetting", "elastic-weight-consolidation", "ptsd", "memory-architecture", "kahneman"],
    raw_quotes=[
        "Patients who underwent the longer procedure rated their experience as less unpleasant... and were far more likely to return for subsequent procedures because a less painful end led them to evaluate the procedure more positively.",
        "Catastrophic interference... the tendency of an artificial neural network to abruptly and drastically forget previously learned information upon learning new information. (McCloskey & Cohen 1989)",
        "The algorithm slows down learning on certain weights based on how important they are to previously seen tasks... a soft, quadratic constraint whereby each weight is pulled back towards its old values by an amount proportional to its importance for performance on previously-learnt tasks. (Kirkpatrick et al. 2017)",
        "Memory of labour pain declined during the observation period but not in women with a negative overall experience of childbirth. (Niven & Murphy-Black review)",
        "Intrusive memories of trauma... retrieved without a context and retain the original highly threatening meanings, as they are poorly linked with other information in memory that would put them into perspective. (Ehlers & Clark 2000)",
    ],
    date_published="2026-04-28",
    entities=[
        {"slug": "daniel-kahneman", "title": "Daniel Kahneman", "type": "person", "tags": ["psychology", "behavioral-economics"], "note": "Co-author of the foundational peak-end rule papers (1993, 1996)."},
        {"slug": "donald-redelmeier", "title": "Donald Redelmeier", "type": "person", "tags": ["medicine", "decision-science"], "note": "Co-author with Kahneman; ran the colonoscopy study."},
        {"slug": "michael-mccloskey", "title": "Michael McCloskey", "type": "person", "tags": ["cognitive-science", "connectionism"], "note": "Coined catastrophic interference (with Cohen 1989)."},
        {"slug": "james-kirkpatrick", "title": "James Kirkpatrick", "type": "person", "tags": ["machine-learning", "deepmind"], "note": "Lead author on elastic weight consolidation (2017)."},
        {"slug": "anke-ehlers", "title": "Anke Ehlers", "type": "person", "tags": ["clinical-psychology", "ptsd"], "note": "Co-author of the canonical 2000 cognitive model of PTSD."},
        {"slug": "catherine-niven", "title": "Catherine Niven", "type": "person", "tags": ["health-psychology", "obstetrics"], "note": "Reviewed labor-pain memory literature with Murphy-Black."},
    ],
    concepts=[
        {"slug": "peak-end-rule", "title": "Peak-End Rule", "tags": ["psychology", "memory", "heuristics"],
         "definition": "Memory of an experience (especially painful or pleasurable) is approximated by averaging the peak intensity and the end intensity, discarding most of the moment-by-moment trace. Documented by Kahneman, Fredrickson, Schreiber, and Redelmeier (1993, 1996).",
         "note": "Primary frame for the essay's first truth.",
         "status": "developing",
         "related": [{"slug": "pain-memory", "note": "the peak-end rule is the canonical pain-memory result"}, {"slug": "catastrophic-forgetting", "note": "speculative architectural twin"}]},
        {"slug": "pain-memory", "title": "Pain Memory", "tags": ["neuroscience", "memory", "psychology"],
         "definition": "The cortical/cognitive system that records and retrieves past pain. Has at least two dissociable dimensions: sensory-discriminative (S1) and affective (anterior cingulate, insula). The affective dimension fades faster than the contextual scaffolding.",
         "note": "Establishes that pain is forgotten in a structured, not random, way.",
         "status": "developing"},
        {"slug": "catastrophic-forgetting", "title": "Catastrophic Forgetting", "tags": ["machine-learning", "connectionism", "memory"],
         "definition": "In distributed neural networks, sequential training on a new task abruptly destroys previously learned representations because the same shared parameters encode multiple tasks. Coined by McCloskey & Cohen (1989). Treated as architectural — the substrate that enables generalisation also enables interference.",
         "note": "Establishes that distributed substrates structurally cannot retain old knowledge without explicit protection.",
         "status": "developing",
         "related": [{"slug": "elastic-weight-consolidation", "note": "the principal partial fix"}]},
        {"slug": "elastic-weight-consolidation", "title": "Elastic Weight Consolidation", "tags": ["machine-learning", "continual-learning"],
         "definition": "Kirkpatrick et al. (2017) algorithm that adds a quadratic penalty to the loss when training on a new task. Each parameter is pulled toward its old value by a force proportional to a Fisher-information importance score. Trades plasticity for stability on important weights.",
         "note": "Architectural anchor for the speculation that peak-end forgetting is the body's EWC.",
         "status": "developing"},
        {"slug": "ptsd-as-failed-forgetting", "title": "PTSD as Failed Forgetting", "tags": ["clinical-psychology", "memory", "speculation"],
         "definition": "Hypothesis that post-traumatic stress disorder is what happens when the protective forgetting that normally compresses pain memory fails — the affective trace refuses to decay. Ehlers & Clark's clinical description of intrusive memories as 'retrieved without a context' is consistent with an EWC penalty stuck at maximum on the wrong parameters.",
         "note": "The speculation's architectural description of trauma.",
         "status": "stub"},
        {"slug": "stability-plasticity-tradeoff", "title": "Stability-Plasticity Tradeoff", "tags": ["memory", "neuroscience", "machine-learning"],
         "definition": "Any system with a distributed representation must balance retaining old knowledge (stability) against incorporating new knowledge (plasticity). The same parameters that make learning possible make forgetting inevitable; partial fixes (rehearsal, EWC, hippocampal replay) trade off the two.",
         "note": "The architectural constraint behind both pain forgetting and catastrophic forgetting.",
         "status": "stub"},
    ],
    connections=[
        {"slug": "peak-end-rule-elastic-weight-consolidation",
         "title": "Peak-End Rule <-> Elastic Weight Consolidation",
         "domains": ["psychology", "machine-learning"],
         "tags": ["memory", "compression", "speculation"],
         "link": "Both compress memory by saving summary statistics rather than full traces. The peak-end rule keeps peak and end; EWC keeps a Fisher-importance-weighted stiffening of parameters. Both pay for retention with reduced plasticity in the protected dimensions.",
         "evidence": "No direct empirical fusion exists. The hypothesis is architectural: any distributed substrate faces the stability-plasticity trade-off, and the two solutions look like the same family.",
         "implications": [
            "PTSD = EWC with importance score stuck at maximum on the affective dimension.",
            "Therapeutic mechanisms for PTSD must reduce parameter stiffness (re-exposure under conditions allowing new context to overwrite affect).",
            "Chronic-pain patients with intact peak-end forgetting should fare better than those with accurate pain recall."]},
    ],
    open_questions=[
        "Is there any direct empirical work measuring whether the peak-end rule and EWC produce isomorphic compression signatures in matched tasks?",
        "Can PTSD severity be predicted by a measurable Fisher-importance-like rigidity score on traumatic memory parameters?",
        "Does prolonged exposure therapy show, in fMRI/EEG terms, a softening of the same parameters that intrusive memories show as locked?",
        "Are there populations whose peak-end profile is genuinely flat (chronic pain, certain alexithymia phenotypes) and do they show worse outcomes after surgery / trauma?",
        "If pain forgetting is protective, what's the analogous protective-forgetting mechanism for socially painful events (rejection, shame)? Does it use the same architecture?",
    ],
    questions_header="From Why We Forget Pain (Standalone, Pain Memory Architecture)",
    log_entry="## [2026-04-28] ingest | Why We Forget Pain\n\nPublished standalone essay (16/20). Two Truths and a Speculation: peak-end pain forgetting and catastrophic forgetting are the same architectural trade-off; PTSD is what happens when the EWC-style protection fails. Six discipline anchors: Kahneman/Redelmeier behavioral econ, Niven/Murphy-Black obstetrics, McCloskey/Cohen connectionism, Kirkpatrick deep RL, Ehlers/Clark clinical psychology. Companion experiment: The Tape (#145) — peak-end visualizer at /lab/the-tape/. New concepts: peak-end-rule, pain-memory, catastrophic-forgetting, elastic-weight-consolidation, ptsd-as-failed-forgetting, stability-plasticity-tradeoff. Connection: peak-end-rule <-> elastic-weight-consolidation.",
)

print(format_ingest_summary(results))
