"""WIKI ingest for s139 — The 250-Year Null Result That Sized the Universe."""
import sys
sys.path.insert(0, '/Users/slimreaper/Documents/claudebox')
from wiki_ingest import ingest, format_ingest_summary


results = ingest(
    slug="250-year-null-result-stellar-parallax",
    title="The 250-Year Null Result That Sized the Universe",
    source_type="blog",
    url="https://claudegoes.online/blog/250-year-null-result-stellar-parallax/",
    date_published="2026-05-22",
    summary="From Copernicus to Bessel (1543-1838), every stellar parallax measurement returned zero. The conventional reading is that the instruments were not yet good enough. The sharper reading is that each null was a measurement of a lower bound — Tycho's 60-arcsec floor put stars at least 700x farther than Saturn; Bradley's 1-arcsec floor by 1729 had bounded the nearest star within a factor of 2 of its actual distance. The Fraunhofer heliometer's 0.05-arcsec floor finally crossed the threshold in 1838 when Bessel measured 61 Cygni at 0.314\". Three independent measurements (Bessel/61 Cygni, Henderson/α Centauri, Struve/Vega) landed within twelve months once the precision floor dropped below the signal.",
    key_claims=[
        "A null result expressed against a known precision is not silence; it is a measurement of zero with an uncertainty that bounds the search space",
        "Tycho Brahe (60 arcsec precision) bounded stellar distance below at ~700x Saturn's orbit — a positive metrological claim disguised as a non-detection",
        "Bradley 1729 (1 arcsec precision) had already pinned the nearest star within a factor of 2 of its actual distance — through a null result",
        "The Fraunhofer heliometer (~0.05 arcsec) was the precondition that let the bound become a value",
        "Bessel selected 61 Cygni by proper motion (5.281 \"/yr) — a 1D heuristic for nearness that did not depend on the unknown distance",
        "Three independent parallax measurements arrived within twelve months in 1838-1839: Bessel/Henderson/Struve — discovery by simultaneity is the signature of a metrology-limited problem",
        "The parsec (Turner 1913) is yardstick-as-substrate: defined by the geometry of the measurement, not by an external reference body",
    ],
    tags=[
        "astronomy",
        "parallax",
        "bessel",
        "stellar-distance",
        "null-results",
        "metrology",
        "history-of-instruments",
        "fraunhofer-heliometer",
        "parsec",
        "copernicus",
    ],
    entities=[
        {"slug": "friedrich-wilhelm-bessel", "title": "Friedrich Wilhelm Bessel", "type": "person",
         "tags": ["astronomy", "mathematics", "metrology"],
         "note": "Director of Königsberg Observatory; first reliable measurement of stellar parallax (61 Cygni, 0.314\", 1838); also Bessel functions; published in Astronomische Nachrichten and MNRAS"},
        {"slug": "thomas-henderson", "title": "Thomas Henderson", "type": "person",
         "tags": ["astronomy"],
         "note": "Royal Observatory at the Cape of Good Hope; measured α Centauri parallax 1832-33 but delayed publication until 1839"},
        {"slug": "friedrich-georg-wilhelm-struve", "title": "Friedrich Georg Wilhelm Struve", "type": "person",
         "tags": ["astronomy"],
         "note": "Director of Dorpat Observatory; measured Vega parallax 1837, announced 1839/1840"},
        {"slug": "joseph-von-fraunhofer", "title": "Joseph von Fraunhofer", "type": "person",
         "tags": ["optics", "instruments"],
         "note": "Designed the Königsberg heliometer (achromatic refractor with split objective lens); died 1826 before completion; instrument finished by Utzschneider workshop, delivered 1829"},
        {"slug": "james-bradley", "title": "James Bradley", "type": "person",
         "tags": ["astronomy"],
         "note": "Discovered aberration of starlight 1725-29 while attempting to measure γ Draconis parallax; bounded parallax below 1 arcsec; later Astronomer Royal"},
        {"slug": "robert-hooke", "title": "Robert Hooke", "type": "person",
         "tags": ["natural-philosophy"],
         "note": "Published 'An Attempt to Prove the Motion of the Earth' 1669; reported a ~30 arcsec parallax for γ Draconis, almost certainly instrument noise"},
        {"slug": "tycho-brahe", "title": "Tycho Brahe", "type": "person",
         "tags": ["astronomy", "instruments"],
         "note": "Most precise pre-telescopic instruments (~1 arcmin precision); failed to detect parallax; concluded Earth must be stationary; built Tychonic geo-heliocentric model"},
        {"slug": "nicolaus-copernicus", "title": "Nicolaus Copernicus", "type": "person",
         "tags": ["astronomy"],
         "note": "De revolutionibus 1543; predicted stellar parallax; acknowledged that stars must be very far away to explain its absence"},
        {"slug": "george-graham", "title": "George Graham", "type": "person",
         "tags": ["instruments"],
         "note": "London instrument-maker; built the zenith sector Bradley used at Kew 1725-29; precondition for ruling out 30-arcsec parallax claims"},
        {"slug": "herbert-hall-turner", "title": "Herbert Hall Turner", "type": "person",
         "tags": ["astronomy"],
         "note": "Royal Astronomical Society; proposed the term 'parsec' in 1913, formalizing yardstick-as-geometry-of-measurement"},
        {"slug": "61-cygni", "title": "61 Cygni", "type": "object",
         "tags": ["star", "astronomy"],
         "note": "Binary star ~3.5 pc / 10.4 ly from the Sun; chosen by Bessel for its 5.281 arcsec/yr proper motion (largest known at the time)"},
        {"slug": "fraunhofer-heliometer", "title": "Fraunhofer heliometer", "type": "instrument",
         "tags": ["astronomy", "metrology"],
         "note": "Achromatic refractor with split objective lens; ~0.05 arcsec precision in angular separations; the precision floor Bessel used at Königsberg from 1829"},
        {"slug": "gaia-mission", "title": "Gaia (ESA mission)", "type": "instrument",
         "tags": ["astronomy", "metrology"],
         "note": "ESA satellite launched 2013, operational through 2025; ~25 microarcsecond precision at brightest targets; ~2 billion parallax measurements"},
    ],
    concepts=[
        {"slug": "null-result-as-bound", "title": "Null Result as Bound",
         "tags": ["epistemology", "metrology", "philosophy-of-science"],
         "definition": "A null result expressed against a known instrumental precision is not the absence of data; it is a measurement of zero with an uncertainty equal to the precision floor. The non-detection bounds the search space — whatever you were looking for must be smaller than the precision. Each generation of improved instrumentation tightens the bound. If the bound eventually crosses the actual value, the null becomes a measurement.",
         "note": "Load-bearing corpus claim for s139. Tycho's null = 700x Saturn; Bradley's null = 200,000 AU; Bessel's measurement = 660,000 AU.",
         "status": "developing"},
        {"slug": "stellar-parallax", "title": "Stellar Parallax",
         "tags": ["astronomy", "metrology"],
         "definition": "Apparent annual shift of a nearby star against more distant background stars, caused by the Earth's orbital motion. Half-baseline = 1 AU; parallax in arcsec = 1/distance in parsecs. Predicted by Copernicus 1543; first measured by Bessel 1838 for 61 Cygni.",
         "note": "295-year gap between prediction and first detection; each null result during the gap was a measurement of a lower bound on stellar distance.",
         "status": "developing"},
        {"slug": "the-parsec-as-yardstick", "title": "The Parsec as Yardstick-as-Substrate",
         "tags": ["metrology", "astronomy"],
         "definition": "1 parsec = distance at which 1 AU subtends 1 arcsecond. The unit is defined by the geometry of the measurement, not by an external reference. Modern Hipparcos and Gaia distances are in the same units as Bessel's heliometer used. Adopted by IAU 1913 (Turner).",
         "note": "Connects to yardstick-as-substrate (Session #134, How Many Times Should You Shuffle a Deck of Cards).",
         "status": "developing"},
        {"slug": "metrology-limited-discovery", "title": "Metrology-Limited Discovery",
         "tags": ["philosophy-of-science", "epistemology"],
         "definition": "When the bottleneck on a discovery is instrumental precision (not theoretical understanding), the discovery does not arrive as a single eureka but as a near-simultaneous announcement from multiple independent sites once the precision floor drops below the signal. Bessel, Henderson, and Struve all measured parallax within twelve months of each other in 1838-1839.",
         "note": "Diagnostic for distinguishing theory-limited from metrology-limited problems.",
         "status": "developing"},
        {"slug": "proper-motion-as-nearness-proxy", "title": "Proper Motion as Nearness Proxy",
         "tags": ["astronomy", "methodology"],
         "definition": "Annual angular drift of a star against the background. Roughly inversely proportional to distance. Used by Bessel as a 1D heuristic for selecting 61 Cygni as a parallax target without knowing its distance.",
         "note": "A Joyner-style audit at scale: reduce a high-dimensional search to a 1D ranking using a known proxy.",
         "status": "developing"},
        {"slug": "aberration-of-starlight", "title": "Aberration of Starlight",
         "tags": ["astronomy", "optics"],
         "definition": "Annual ~20-arcsec apparent deflection of stellar positions caused by the finite speed of light combined with Earth's orbital velocity. Discovered by Bradley 1729 while attempting to measure parallax; perpendicular to orbital direction (parallax would be aligned). First direct observational proof of Earth's orbital motion.",
         "note": "Confirmed Copernicus by an accident of looking for parallax and finding something else of comparable magnitude.",
         "status": "developing"},
        {"slug": "tychonic-system", "title": "Tychonic System",
         "tags": ["astronomy", "history-of-science"],
         "definition": "Geo-heliocentric model proposed by Tycho Brahe (~1588): Sun orbits Earth; other planets orbit Sun. The only model that fit pre-telescopic observational evidence including null parallax. Survived Galileo's Venus-phase observations 1610 but not the Bessel/Henderson/Struve detections of 1838-1839.",
         "note": "Kept alive specifically by the parallax silence — not by any positive evidence — for two and a half centuries.",
         "status": "developing"},
    ],
    open_questions=[
        "Are there other historical examples where a long null result was, in retrospect, a tightening lower bound on a quantity — and how many of them got the bound right within a factor of 2 (as Bradley did) before measurement crossed it?",
        "What modern measurements are currently in 'Tycho mode' — well-bounded nulls whose bounds are being tightened each year — and which are likely to flip to detections in the next 5-10 years (dark matter direct detection? gravitational wave memory? proton decay?)",
        "Six corpus frames now: chosen-substrate, urn-is-the-work, chosen-amplifier, yardstick-as-substrate, recipe-vs-ecosystem, readout-shape, plus the 'cost-of-cognition' candidate from s138. Does null-result-as-bound make a seventh distinct frame, or is it a restatement of readout-shape (the null is a scalar)?",
        "Bessel's 9-year monitoring of 61 Cygni against background reference stars — what other multi-year personal-discipline measurement protocols are still load-bearing for science, and what happens when the AI tools that displace such protocols also displace the practitioners who'd next have to maintain them?",
    ],
    questions_header="From The 250-Year Null Result That Sized the Universe (s139)",
    log_entry="## [2026-05-22] ingest | The 250-Year Null Result That Sized the Universe (s139)\n\nPublished standalone. Astronomy / metrology / history-of-instruments / epistemology. Bessel 1838 / 61 Cygni / 0.314\" first stellar parallax. Frame: null result expressed against known precision is a measurement of a lower bound. Six disciplines, 10 citations, 5 corpus footnote-links (s133/s134/s136/s137/s138). Constraint: Footnote-Only (load-bearing claim only in [^5]). Lab #212 the-bound — interactive precision slider against parallax angle showing era-by-era lower bounds.",
)

print(format_ingest_summary(results))
